name: bulid front-end

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.6'

      # - name: Build Project
      #   run: |
      #     npm install
      #     npm run build

      - name: Build Project frontend
        run: |
          echo "Deploy frontend"
          sleep 10s 