name: Push to master

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Get latest code
        uses: actions/checkout@v3

      - name: Verificar Alterações no package.json ou package-lock.json
        run: |
          if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- package.json package-lock.json) ]]; then
              echo "changes=true" >> $GITHUB_ENV
          else
              echo "changes=false" >> $GITHUB_ENV
          fi
      
      - name: Install Dependencies (If Changes Detected)
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          echo "Changes detected, so running this step."
  
      - name: Install Dependencies (If Changes not Detected)
        if: steps.check-changes.outputs.changes == 'false'
        run: |
            echo "Changes not detected, so running this step."
     