name: deploy to a server back-end

on:
  push:
    branches: [ main ]

  workflow_dispatch 

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      - name: Generate environment test
        run: |
          cd src
          mkdir ./environments
          touch text.txt
          cd environments

      - name: Generate environment homolog        
        run: |
          cd ..
          ls        
          
          
          
      
          

        # wget https://swupdate.openvpn.org/community/releases/openvpn-2.4.7.tar.gz
        # tar xfz openvpn-2.4.7.tar.gz 
        #cd openvpn-2.4.7 
        #./configure

      # - name: Install OpenVPN
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get --assume-yes --no-install-recommends install openvpn

      # - name: Setup VPN config
      #   run: |
      #     echo "${{ secrets.SECRET_USERNAME_PASSWORD }}" > secret.txt
      # - name: Connect VPN
      #   run: |
      #     sudo openvpn --config ".github/vpn/safiragit__ssl_vpn_config.ovpn" --log "vpn.log" --daemon
      # - name: Wait for a VPN connection
      #   timeout-minutes: 1
      #   run: |
      #     until ping -c1 ${{ secrets.FTP_SERVER }}; do sleep 2; done

      - name: Build Project frontend
        run: |
          echo "Deploy frontend"
          sleep 10s 