name: Verificar Alterações no package.json

on:
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check for changes in package.json
        id: check-package-json
        uses: changesets/action@v3
        with:
          file-paths: package.json

      - name: Print result
        run: |
          if ${{ steps.check-package-json.outputs.changed }} == 'true'; then
            echo "Changes detected in package.json."
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected in package.json."
            echo "changes=false" >> $GITHUB_ENV
          fi