# - name: Checkout
#   uses: actions/checkout@v3
#   with:
#      fetch-depth: 2
# - name: Get changes
#   run: git diff --name-only -r HEAD^1 HEAD

name: Verificar Alterações no arquivo package.json

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout o repositório
        uses: actions/checkout@v2

      - name: Get changes in package.json
        id: get-changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'package.json'

      - name: Check for changes in package.json
        id: check-package-json
        run: |
          if [[ -n "${{ steps.get-changes.outputs.stdout }}" ]]; then
            echo "Changes detected in package.json."
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected in package.json."
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Print result
        run: |
          if [[ "${{ env.changes }}" == "true" ]]; then
            echo "Changes detected in the last Pull Request."
          else
            echo "No changes detected in the last Pull Requests."
          fi