name: Verificar Alterações no arquivo package.json

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout o repositório
        uses: actions/checkout@v2

      - name: Check for changes in package.json
        id: check-package-json
        run: |
          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'package.json') ]]; then
          echo "true" 
          echo "::set-env name=changespack::true"
          else
          echo "false" 
          echo "::set-env name=changespack::false"
          fi

      