name: Verificar Alterações no arquivo package.json

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout o repositório
        uses: actions/checkout@v2

      - name: Get changes for PR
        run: |
          CHANGES=$(git diff --name-only origin/main...${{ github.event.pull_request.head.ref }})
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV

      - name: Compare changes
        run: |
          if [[ "${{ env.CHANGES }}" == *"package.json"* ]]; then
            echo "O arquivo package.json foi modificado na PR atual em relação à branch principal."
            # Adicione comandos adicionais que você deseja executar com base na alteração do package.json.
          else
            echo "O arquivo package.json não foi modificado na PR atual em relação à branch principal."
          fi
